services:
  backend:
    build: ./src/
    ports: 
      - "8000:8000" 
    restart: always
    command: bash -c "
      uvicorn main:app --host 0.0.0.0 --port 8000 --loop asyncio"
    env_file:
      - ./src/.env
    volumes:
      - ./src/:/code

