# Generated by Django 5.1.4 on 2025-03-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='user_preference',
            new_name='prompt',
        ),
    ]
