# Generated by Django 5.1.4 on 2025-03-20 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_rename_user_preference_prompt_prompt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='prompt',
            new_name='topic',
        ),
    ]
