# Generated by Django 5.1.4 on 2025-04-01 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_rename_prompt_prompt_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='prompt_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
